### PR TITLE
Add Build pipeline and remove old GitLab resources

### PR DESCRIPTION
**Pull request by dasGoogle**

### CODE REVIEW

**Comment by dasGoogle** [comment]
Please squash when merging

**Comment by Sohn123** [comment]
Where do I find the packages now?

**Comment by dasGoogle** [comment]
> Where do I find the packages now?

In each workflow summary

**Comment by Sohn123** [comment]
> > Where do I find the packages now?
> 
> In each workflow summary

Ah ok found it

**Pull request merged**
